# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master
- release/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet restore
  displayName: Restore packages

- script: dotnet build -c $(BuildConfiguration) --no-restore
  displayName: Build

- script: dotnet pack -c $(BuildConfiguration) --no-build
  displayName: Pack

- task: CopyFiles@2
  displayName: Collect packages
  inputs:
    SourceFolder: src/NCalcAsync/bin/$(BuildConfiguration)
    Contents: |
      *.nupkg
      *.snupkg
    TargetFolder: $(Build.ArtifactStagingDirectory)/Packages
  condition: eq(variables['BuildConfiguration'], 'Release')

- task: PublishBuildArtifacts@1
  displayName: Publish packages as build artifacts
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)/Packages
    ArtifactName: Packages
    publishLocation: Container
  condition: eq(variables['BuildConfiguration'], 'Release')

- task: DotNetCoreCLI@2
  displayName: Run unit tests
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
